# See docs/config.md for documentation on the different parameters in this file

# == Basic configuration ==

# (optional) Enable building osbuildvm-images
# Leave undefined or set to false to disable
# Resulting VM architecture is based on the build host
target_image: ""
target_arch: aarch64
target_filetype: ""

osbuildvm_images_build: yes

# == Advanced configuration ==
osbuildvm_images_download_baseurl: "https://autosd.sig.centos.org/AutoSD-9/nightly/osbuildvm-images"

osbuild_packages:
  - package: "osbuild"
    value: "osbuild"
  - package: "osbuild-tools"
    value: "osbuild-tools"
  - package: "osbuild-ostree"
    value: "osbuild-ostree"
  - package: "osbuild-auto"
    value: "osbuild-auto"

sample_images_git_url: "https://gitlab.com/CentOS/automotive/sample-images.git"
sample_images_git_ref: "main"
sample_images_workdir: "{{ ansible_env.HOME }}/zeppelin/sample-images"
sample_images_build_path: "{{ sample_images_workdir }}/osbuild-manifests/_build"

# Hetzner Cloud configuration
hcloud_aarch64_server_type: "cax21"
hcloud_aarch64_image: "centos-stream-9"
hcloud_aarch64_location: "fsn1"
hcloud_aarch64_ssh_keys:
  - "ci@asz"

hcloud_x86_64_server_type: "cx21"
hcloud_x86_64_image: "centos-stream-9"
hcloud_x86_64_location: "fsn1"
hcloud_x86_64_ssh_keys:
  - "ci@asz"
