---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  become: yes

- name: Clone sample-images project
  ansible.builtin.git:
    repo: "{{ sample_images_git_url }}"
    dest: "{{ sample_images_path }}"
    version: "{{ sample_images_git_ref }}"
  ignore_errors: true
  register: results

- name: Write log files
  copy:
    content: "{{ results }}"
    dest: "./out/log.clone_sample_images.txt"
  delegate_to: localhost

- name: Error handler
  debug:
    var: results
  failed_when: true
  when:
    results is failed
