# See docs/config.md for documentation on the different parameters in this file

# == Basic configuration ==

target_image: cs9-qemu-qa-ostree
target_arch: x86_64
target_filetype: img

custom_images_git_url: "https://gitlab.com/redhat/edge/ci-cd/pipe-x/custom-images.git"
custom_images_git_ref: "main"
custom_images_workdir: "{{ ansible_env.HOME }}/zeppelin/custom-images"

# Force to use local copy of custom-images
# Leave undefined to clone from custom_images_git_url
# local_custom_images: "{{ ansible_env.HOME }}/custom-images"

# == Advanced configuration ==
osbuild_vmimages_download_baseurl: "https://autosd.sig.centos.org/AutoSD-9/nightly/osbuildvm-images"

osbuild_packages:
  - package: "osbuild"
    value: "osbuild"
  - package: "osbuild-tools"
    value: "osbuild-tools"
  - package: "osbuild-ostree"
    value: "osbuild-ostree"
  - package: "osbuildtest-ostree-compliance-mode"
    value: "osbuildtest-ostree-compliance-mode"

sample_images_git_url: "https://gitlab.com/CentOS/automotive/sample-images.git"
sample_images_git_ref: "main"
sample_images_path: "{{ ansible_env.HOME }}/sample-images"
sample_images_build_path: "{{ sample_images_path }}/osbuild-manifests/_build"

# Hetzner Cloud configuration
hcloud_aarch64_server_type: "cax21"
hcloud_aarch64_image: "centos-stream-9"
hcloud_aarch64_location: "fsn1"
hcloud_aarch64_ssh_keys:
  - "michael@fedora"

hcloud_x86_64_server_type: "cx21"
hcloud_x86_64_image: "centos-stream-9"
hcloud_x86_64_location: "fsn1"
hcloud_x86_64_ssh_keys:
  - "michael@fedora"
