---
- name: instantiate-builder
  hosts: localhost
  roles:
    - hetzner-cloud-instantiate

- name: initiate build
  hosts: "asz_server"
  remote_user: root
  roles:
    - common

- name: clone sample images
  hosts: "asz_server"
  remote_user: root
  roles:
    - clone-sample-images

- name: prepare custom images
  hosts: "asz_server"
  remote_user: root
  roles:
    - prepare-custom-images

- name: prepare osbuild
  hosts: "asz_server"
  remote_user: root
  roles:
    - prepare-osbuild

- name: run make
  hosts: "asz_server"
  remote_user: root
  roles:
    - run-make

- name: teardown-builder
  hosts: localhost
  roles:
    - hetzner-cloud-teardown
