---
- name: initiate build
  hosts: localhost
  roles:
    - common

- name: clone sample images
  hosts: localhost
  roles:
    - clone-sample-images

- name: clone custom images
  hosts: localhost
  roles:
    - clone-custom-images

- name: prepare osbuild
  hosts: localhost
  roles:
    - prepare-osbuild

- name: run make
  hosts: localhost
  roles:
    - run-make
