---
- name: initiate build
  hosts: localhost
  roles:
    - common

- name: prepare sample images
  hosts: localhost
  roles:
    - prepare-sample-images

- name: prepare custom images
  hosts: localhost
  roles:
    - prepare-custom-images

- name: prepare distro configs
  hosts: localhost
  roles:
    - prepare-distro-configs

- name: prepare osbuild
  hosts: localhost
  roles:
    - prepare-osbuild

- name: run make
  hosts: localhost
  roles:
    - run-make

- name: run make for osbuildvm-images
  hosts: localhost
  roles:
    - run-make-osbuildvm
