---
- name: load variables
  ansible.builtin.include_vars: ../../../config.yaml

# Instantiate hetzner server
- include_tasks: instantiate_builder.yaml 

- meta: refresh_inventory

- name: wait_for_connection
  wait_for_connection:
    delay: 5
    timeout: 600
  delegate_to: my-server
  remote_user: root
