---
- name: decide make params
  set_fact:
    run_make_params:
      IMAGEDIR: "{{ custom_images_workdir if custom_images_workdir is defined else '' }}"

- name: run make
  become: yes
  make:
    chdir: "{{ sample_images_workdir }}/osbuild-manifests"
    target: "{{ target_image }}.{{ target_arch }}.{{ target_filetype }}"
    params: "{{ run_make_params|dict2items|rejectattr('value', 'equalto', '')|list|items2dict }}"
  ignore_errors: true
  register: results

- name: Write log files
  copy:
    content: |
      chdir: {{ sample_images_workdir }}/osbuild-manifests
      target: {{ target_image }}.{{ target_arch }}.{{ target_filetype }}
      params: {{ run_make_params|dict2items|rejectattr('value', 'equalto', '')|list|items2dict }}
      {{ results.stdout }}
    dest: "./out/log.run_make.txt"
  delegate_to: localhost

- name: Error handler
  debug:
     var: results
  failed_when: true
  when:
     results is failed

- name: gather output (image)
  fetch:
    src: "{{ sample_images_workdir }}/osbuild-manifests/{{ target_image }}.{{ target_arch }}.{{ target_filetype }}"
    dest: "./out/"
    flat: yes

- name: gather output (osbuild json)
  fetch:
    src: "{{ sample_images_build_path }}/{{ target_image }}.{{ target_arch }}.json"
    dest: "./out/"
    flat: yes
