---
- name: Create a security group for ssh access to builder instances
  amazon.aws.ec2_security_group:
    name: "asz-security-group-ssh"
    description: security group for ssh access to asz builders
    region: "{{ aws_ec2_aarch64_region if target_arch == 'aarch64' else aws_ec2_x86_64_region }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22
    state: present

- name: Create a basic ec2 instance with ssh key
  amazon.aws.ec2_instance:
    name: "asz-server-{{ server_id }}"
    key_name: "{{ aws_ec2_aarch64_ssh_key if target_arch == 'aarch64' else aws_ec2_x86_64_ssh_key }}"
    instance_type: "{{ aws_ec2_aarch64_instance_type if target_arch == 'aarch64' else aws_ec2_x86_64_instance_type }}"
    image_id: "{{ aws_ec2_aarch64_ami if target_arch == 'aarch64' else aws_ec2_x86_64_ami }}"
    region: "{{ aws_ec2_aarch64_region if target_arch == 'aarch64' else aws_ec2_x86_64_region }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 20
          delete_on_termination: true
    network:
      assign_public_ip: true
      delete_on_termination: true
    security_groups:
      - "asz-security-group-ssh"
    tags:
      asz: "1"
    state: running
    wait: true
