---
- name: load variables
  ansible.builtin.include_vars: ../../../config.yaml

# Prepare server id
- name: prepare random server id
  ansible.builtin.set_fact:
    server_id: "{{ lookup('community.general.random_string', length=4, special=false) }}"

- name: debug server id
  ansible.builtin.debug:
    msg: "server id: {{ server_id }}"

# Instantiate ec2 instance
- include_tasks: instantiate_builder.yaml

- meta: refresh_inventory

- name: prepare ansible hosts group for playbook usage
  ansible.builtin.add_host:
    name: "asz-server-{{ server_id }}"
    groups: "asz_server"

- name: debug ansible host ip
  ansible.builtin.debug:
    msg: "{{ hostvars['asz-server-'+server_id].public_ip_address }}"

- name: wait_for_connection
  ansible.builtin.wait_for:
    port: 22
    host: "{{ hostvars['asz-server-'+server_id].public_ip_address }}"
    delay: 30
    connect_timeout: 60
    timeout: 300
  remote_user: ec2-user
