---
- name: Print OS and distro Ansible variables collected by setup
  debug:
    msg:
      - "ansible_os_family: {{ ansible_os_family }}"
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_distribution_version: {{ ansible_distribution_version }}"
      - "ansible_distribution_release: {{ ansible_distribution_release }}"

# TODO: end playbook if unsupported distro encountered
- name: Install general dependencies
  become: yes
  ansible.builtin.dnf:
    name:
      - make
      - skopeo

- name: Enable OSBuild copr
  become: yes
  community.general.copr:
    state: enabled
    name: '@osbuild/osbuild'

- name: Install OSBuild rpms
  become: yes
  ansible.builtin.dnf:
    name:
      - osbuild
      - osbuild-tools
      - osbuild-ostree

- name: Enable ostree-compliance-mode copr
  become: yes
  community.general.copr:
    state: enabled
    name: 'ecurtin/osbuildtest-ostree-compliance-mode'

- name: Install ostree-compliance-mode
  become: yes
  ansible.builtin.dnf:
    name:
      - osbuildtest-ostree-compliance-mode

- name: Enable osbuild-aboot copr
  become: yes
  community.general.copr:
    state: enabled
    name: 'alexl/osbuild-aboot'

- name: Enable abootimg copr
  become: yes
  community.general.copr:
    state: enabled
    name: 'alexl/abootimg'
    chroot: epel-9-{{ ansible_architecture }}

- name: Install abootimg and aboot-update
  become: yes
  ansible.builtin.dnf:
    name:
      - abootimg
      - aboot-update

- name: Prepare _build directory
  become: yes
  ansible.builtin.file:
    path: "{{ sample_images_build_path }}"
    state: directory

- name: Download osbuildvm-images
  become: yes
  ansible.builtin.get_url:
    url: "{{ osbuild_vmimages_download_baseurl }}/{{ item }}"
    dest: "{{ sample_images_build_path }}/{{ item }}"
    mode: 0644
  when: target_arch == "aarch64" and ansible_architecture == "x86_64"
  with_items:
    - osbuildvm-aarch64.img
    - osbuildvm-aarch64.initramfs
    - osbuildvm-aarch64.vmlinuz
